// CAMPUSES
export const CREATE_CAMPUS = 'CREATE_CAMPUS';
export const EDIT_CAMPUS = 'EDIT_CAMPUS';
export const REMOVE_CAMPUS = 'REMOVE_CAMPUS';
export const ASSIGN_STUDENT_TO_CAMPUS = 'ASSIGN_STUDENT_TO_CAMPUS';
export const REMOVE_STUDENT_FROM_CAMPUS = 'REMOVE_STUDENT_FROM_CAMPUS';

// STUDENTS
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const ASSIGN_CAMPUS_TO_STUDENT = 'ASSIGN_CAMPUS_TO_STUDENT';
export const REMOVE_CAMPUS_FROM_STUDENT = 'REMOVE_CAMPUS_FROM_STUDENT';

